// useful top level imports
pub const image = @import("src/image/image.zig");
pub const bmp = @import("src/image/bmp.zig");
pub const jpg = @import("src/image/jpg.zig");
pub const png = @import("src/image/png.zig");
pub const tga = @import("src/image/tga.zig");
pub const config = @import("src/image/config.zig");
pub const reader = @import("src/image/reader.zig");
pub const types = @import("src/image/types.zig");
pub const time = @import("src/utils/time.zig");

// useful types
pub const RGBA32 = types.RGBA32;
pub const RGB16 = types.RGB16;
pub const RGB15 = types.RGB15;
pub const R8 = types.R8;
pub const R16 = types.R16;
pub const R32 = types.R32;
pub const RGBA128F = types.RGBA128F;
pub const RGBA128 = types.RGBA128;
pub const R32F = types.R32F;
pub const RG64F = types.RG64F;
pub const PixelTag = types.PixelTag;
pub const PixelTagPair = types.PixelTagPair;
pub const I32x2 = types.I32x2;
pub const PixelSlice = types.PixelSlice;
pub const PixelContainer = types.PixelContainer;
pub const Image = types.Image;
pub const ImageLoadOptions = types.ImageLoadOptions;
pub const ImageSaveOptions = types.ImageSaveOptions;
